--
-- File generated with SQLiteStudio v3.3.3 on vie. jun. 4 18:03:17 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: departamentos
DROP TABLE IF EXISTS departamentos;
CREATE TABLE departamentos (id_depto INT PRIMARY KEY UNIQUE NOT NULL, nombre_depto VARCHAR (0, 35) NOT NULL);
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (201, 'Administraci�n');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (202, 'Desarrollo de Software');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (203, 'Quimico en Farmacos');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (204, 'Magia Negra ');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (205, 'Magia Blanca');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (206, 'Alquimia');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (207, 'Rituales de Invocaci�n');
INSERT INTO departamentos (id_depto, nombre_depto) VALUES (208, 'Vision del Futuro');

-- Table: empleados
DROP TABLE IF EXISTS empleados;
CREATE TABLE empleados (id_empleado INT PRIMARY KEY UNIQUE NOT NULL, nombre_empleado VARCHAR (0, 35) NOT NULL, apellido_pa_empleado VARCHAR (0, 20), apellido_ma_empleado VARCHAR (0, 20), correo_empleado STRING UNIQUE NOT NULL, Contrasena STRING NOT NULL, fecha_nacimiento_empleado DATE, fecha_ingreso_empleado DATE NOT NULL, FK_depto_empleado INT REFERENCES departamentos (id_depto) NOT NULL, FK_id_nomina_empleado STRING UNIQUE REFERENCES nomina (id_nomina), FK_id_plantel_empleado INT REFERENCES plantel (id_plantel));
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MARCCG', 'Marciano', 'Cerro', 'Gil', 'MarcianoCG@howarts.com', 'a1b2c3d4', '1995-09-20', '2017-06-14', 202, 3, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('HUJAAM', 'Hugo Jacinto', 'Asensio', 'Molina', 'HujoJAM@howarts.com', 'a1b2c3d4', '1985-11-14', '2020-10-11', 206, 4, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMANCC', 'Amancio', 'Costa', 'Casanovas', 'AmanacioCC@howarts.com', 'a1b2c3d4', '1989-03-06', '2018-01-22', 204, 7, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MARIJP', 'Marita', 'Juli�n', 'Pel�ez', 'MaritaJP@howarts.com', 'a1b2c3d4', '1992-06-16', '2019-02-19', 207, 13, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ALMARH', 'Alma', 'Ribes', 'Heras', 'AlmaRH@howarts.com', 'a1b2c3d4', '1992-09-06', '2019-01-31', 205, 12, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('CELERP', 'Celestino', 'Ros', 'Pe�a', 'CelestinoRP@howarts.com', 'a1b2c3d4', '1984-05-11', '2018-05-14', 201, 11, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('OFELBR', 'Ofelia', 'Bello', 'Rocamora', 'OfeliaBR@howarts.com', 'a1b2c3d4', '1979-07-20', '2019-06-08', 203, 10, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('NOEMRR', 'Noem�', 'Robles', 'Riba', 'Noem�RR@howarts.com', 'a1b2c3d4', '1985-09-13', '2019-10-21', 208, 9, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('NACIFV', 'Nacio', 'Figueras', 'Valero', 'NacioFV@howarts.com', 'a1b2c3d4', '1989-11-17', '2020-09-04', 206, 8, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('NOELTS', 'Noelia', 'Tapia', 'S�ez', 'NoeliaTS@howarts.com', 'a1b2c3d4', '1993-11-15', '2020-04-29', 206, 36, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('GUSTRF', 'Gustavo', 'Riquelme', 'Ferrando', 'GustavoRF@howarts.com', 'a1b2c3d4', '1995-09-18', '2019-02-18', 201, 35, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MACULR', 'M�ximo', 'Llorens', 'Rivero', 'MaximoLR@howarts.com', 'a1b2c3d4', '1983-03-26', '2019-01-14', 202, 34, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('XAVIRB', 'Xavier', 'Robledo', 'Bayo', 'XavierRB@howarts.com', 'a1b2c3d4', '1984-08-05', '2016-06-22', 203, 33, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('LARAOT', 'Lara', 'Oca�a', 'Teruel', 'LaraOT@howarts.com', 'a1b2c3d4', '1989-05-30', '2018-06-11', 208, 32, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('TIBUAD', 'Tiburcio', 'Alatorre', 'del Rueda', 'TiburcioAD@howarts.com', 'a1b2c3d4', '1986-10-12', '2020-01-31', 207, 31, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('CARIIV', 'Carina', 'Isern', 'Villaverde', 'CarinaIV@howarts.com', 'a1b2c3d4', '1988-03-08', '2018-09-04', 205, 30, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMILDT', 'Am�lcar', 'Di�guez', 'Torrecilla', 'AmilcarDT@howarts.com', 'a1b2c3d4', '1986-12-16', '2019-05-13', 204, 29, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('JOSETV', 'Jose Ram�n', 'Torrijos', 'Vilar', 'JoseRTV@howarts.com', 'a1b2c3d4', '1982-05-12', '2019-07-16', 201, 28, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('CUSTCS', 'Custodia', 'Caro', 'Soler', 'CustodiaCS', 'a1b2c3d4', '1984-09-17', '2021-04-06', 204, 27, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('JOAQGT', 'Joaqu�n Efra�n', 'Giralt', 'Torrent', 'JoaquinEGT@howarts.com', 'a1b2c3d4', '1989-11-07', '2018-06-15', 203, 26, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('EPIFCJ', 'Epifanio', 'Cid', 'Jim�nez', 'EpifanioCJ@howarts.com', 'a1b2c3d4', '1990-04-03', '2016-01-12', 201, 59, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('BRUNQB', 'Brunilda', 'Quintana', 'Baquero', 'BrunildaQB@howarts.com', 'a1b2c3d4', '1982-03-04', '2019-05-26', 202, 58, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('GEROVM', 'Ger�nimo', 'Valenciano', 'Mata', 'GeronimoVM@howarts.com', 'a1b2c3d4', '1977-04-13', '2018-05-11', 203, 57, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MACANE', 'Macaria', 'Nevado', 'Escalona', 'MacariaNE@howarts.com', 'a1b2c3d4', '1977-04-11', '2017-03-09', 204, 56, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ROCILP', 'Roc�o', 'Lerma', 'Pardo', 'RocioLP@howarts.com', 'a1b2c3d4', '1983-06-10', '2018-11-25', 205, 55, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('RENAAP', 'Renata', 'Aguilera', 'Palomino', 'RenataAP@howarts.com', 'a1b2c3d4', '1985-09-13', '2018-12-28', 206, 54, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ROBEMA', 'Roberta', 'Montesinos', 'Arnal', 'RobertaMA@howarts.com', 'a1b2c3d4', '1987-09-12', '2019-11-02', 207, 53, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('FLAVNP', 'Flavio', 'Navarro', 'Palau', 'FlavioNP@howarts.com', 'a1b2c3d4', '1991-06-06', '2020-04-13', 208, 52, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MAXIUM', 'Maximino', 'Ure�a', 'Montenegro', 'MaximinioUM@howarts.com', 'a1b2c3d4', '1988-06-16', '2021-04-12', 207, 51, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMPADQ', 'Amparo', 'del Mora', 'Quintana', 'AmparoDQ@howarts.com', 'a1b2c3d4', '1986-04-07', '2020-10-14', 206, 50, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('SAJODA', 'Santiago Jose Miguel', 'Donoso', 'Angulo', 'SantiagoJDA@howarts.com', 'a1b2c3d4', '1989-10-12', '2019-03-11', 205, 49, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMANMA', 'Amando', 'Moliner', '�lvarez', 'AmandoMA@howarts.com', 'a1b2c3d4', '1986-06-09', '2018-01-18', 204, 48, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('CORAMB', 'Coral', 'Mart�n', 'Becerra', 'CoralMB@howarts.com', 'a1b2c3d4', '1989-11-09', '2019-10-18', 203, 47, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('LUZCAT', 'Luz', 'Cases', 'Torrents', 'LuzMB@howarts.com', 'a1b2c3d4', '1989-11-12', '2018-02-19', 202, 46, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ABRIPC', 'Abril', 'Pedro', 'Ca�izares', 'AbrilPC@howarts.com', 'a1b2c3d4', '1987-10-16', '2019-09-15', 201, 45, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('TRINCA', 'Trinidad', 'Caro', 'Arellano', 'TrinidadCA@howarts.com', 'a1b2c3d4', '1987-03-31', '2018-12-18', 205, 60, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AZENMM', 'Azeneth', 'Mur', 'Mosquera', 'AzenethMM@howarts.com', 'a1b2c3d4', '1983-03-07', '2018-04-24', 201, 94, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('GASTBB', 'Gast�n', 'Blanes', 'Bravo', 'GastonBB@howarts.com', 'a1b2c3d4', '1986-03-25', '2019-04-24', 202, 93, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('FELITA', 'Felisa', 'Tejera', 'Alberto', 'FelisaTA@howarts.com', 'a1b2c3d4', '1984-10-17', '2020-06-01', 203, 92, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('GRACMS', 'Graciana', 'Madrid', 'Su�rez', 'GracianaMS@howarts.com', 'a1b2c3d4', '1987-05-01', '2018-12-31', 204, 91, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('GUILBV', 'Guillermo', 'Bar�', 'Viana', 'GuillermoBV@howarts.com', 'a1b2c3d4', '1989-03-14', '2017-09-05', 205, 90, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('HIPOAQ', 'Hip�lito', 'Alem�n', 'Quesada', 'HipolitoAQ@howarts.com', 'a1b2c3d4', '1991-08-15', '2019-11-20', 206, 89, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('PLACBP', 'Pl�cido', 'Bejarano', 'Pel�ez', 'PlacidoBP@howarts.com', 'a1b2c3d4', '1980-11-12', '2015-07-14', 207, 88, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('DARIRS', 'Dar�o', 'Rosell�', 'Salcedo', 'DarioRS@howarts.com', 'a1b2c3d4', '1980-10-22', '2017-07-13', 208, 87, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('VASCCS', 'Vasco', 'Colomer', 'Salda�a', 'VascoCS@howarts.com', 'a1b2c3d4', '1999-06-25', '2020-02-05', 201, 86, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ANTOPA', 'Antonio', 'Pacheco', 'Alberola', 'AntonioPA@howarts.com', 'a1b2c3d4', '1996-04-09', '2020-05-18', 202, 85, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('JOSEAL', 'Jose Manuel', 'Agudo', 'Lozano', 'JoseMAL@howarts.com', 'a1b2c3d4', '1989-03-14', '2019-11-12', 203, 84, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ASDRAS', 'Asdrubal Alfredo', 'Andrade', 'Segarra', 'AsdrubalAAS@howarts.com', 'a1b2c3d4', '1987-08-08', '2018-12-31', 204, 83, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMBASD', '�mbar', 'Su�rez', 'del Oliva', 'AmbarSD@howarts.com', 'a1b2c3d4', '1990-10-16', '2018-05-16', 205, 82, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MIREJE', 'Mireia', 'Jove', 'Escribano', 'MireiaJE@howarts.com', 'a1b2c3d4', '1991-08-15', '2017-07-13', 206, 81, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ABILSM', 'Abilio Emilio', 'Sierra', 'Martinez', 'AbilioESM@howarts.com', 'a1b2c3d4', '1987-09-12', '2020-10-11', 207, 80, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ARISMD', 'Aristides', 'Martinez', 'de Figueroa', 'AristidesMD@howarts.com', 'a1b2c3d4', '1990-04-03', '2018-04-24', 208, 79, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MARTHD', 'Martina', 'Heredia', 'de Lled�', 'MartinaHD@howarts.com', 'a1b2c3d4', '1984-05-11', '2019-11-20', 201, 78, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('BERNCP', 'Bernab�', 'Colomer', 'Pel�ez', 'BernabeCP@howarts.com', 'a1b2c3d4', '1996-12-05', '2016-12-31', 201, 77, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MARIBZ', 'Marisela', 'Barreda', 'Zabala', 'MariselaBZ@howarts.com', 'a1b2c3d4', '1984-05-11', '2015-10-06', 202, 76, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('EDGASA', 'Edgardo', 'Sanchez', 'Anglada', 'EdgardoSA@howarts.com', 'a1b2c3d4', '1990-04-03', '2018-04-24', 203, 75, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('EUFEBG', 'Eufemia', 'Bar�', 'Godoy', 'EufemiaBG@howarts.com', 'a1b2c3d4', '1989-03-14', '2019-04-08', 204, 74, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('TOMASG', 'Tomasa', 'Su�rez', 'Galindo', 'TomasaSG@howarts.com', 'a1b2c3d4', '1990-04-03', '2019-11-20', 205, 73, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('SATUGP', 'Saturnino', 'Garriga', 'Pe�alver', 'SaturninoGP@howarts.com', 'a1b2c3d4', '1987-05-01', '2019-02-18', 206, 72, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('MATIBV', 'Matilde', 'Barriga', 'Vicente', 'MatildeBV@howarts.com', 'a1b2c3d4', '1985-06-12', '2018-02-06', 207, 71, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMPAMD', 'Amparo', 'Modesto', 'de Acero', 'AmparoMD@howarts.com', 'a1b2c3d4', '1984-08-05', '2020-10-11', 205, 70, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('DIEGCD', 'Diego', 'Casal', 'Dom�nguez', 'DiegoCD@howarts.com', 'a1b2c3d4', '1991-08-15', '2018-12-31', 206, 69, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('ANGEBG', 'Angelita', 'Bar�n', 'Guitart', 'AngelitaBG@howarts.com', 'a1b2c3d4', '1985-07-17', '2021-02-03', 201, 68, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('EVAPER', 'Eva', 'Pe�alver', 'Riera', 'EvaPR@howarts.com', 'a1b2c3d4', '1987-09-12', '2017-07-13', 208, 67, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('DANISM', 'Danilo', 'Salas', 'Monta�a', 'DaniloSM@howarts.com', 'a1b2c3d4', '1987-05-01', '2019-11-20', 205, 66, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('RICOFS', 'Rico', 'Frutos', 'Salinas', 'RicoFS@howarts.com', 'a1b2c3d4', '1990-04-03', '2018-12-31', 204, 65, 502);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('VASCPG', 'Vasco', 'Peralta', 'Godoy', 'VascoPG@howarts.com', 'a1b2c3d4', '1984-08-05', '2018-02-19', 203, 64, 501);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('LUISGC', 'Luis Miguel', 'Guzm�n', 'Cuervo', 'LuisMGC@howarts.com', 'a1b2c3d4', '1987-09-12', '2018-12-31', 201, 63, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('AMARIB', 'Amarilis', 'I�iguez', 'Bejarano', 'AmarilisIB@howarts.com', 'a1b2c3d4', '1989-03-14', '2018-02-19', 206, 62, 503);
INSERT INTO empleados (id_empleado, nombre_empleado, apellido_pa_empleado, apellido_ma_empleado, correo_empleado, Contrasena, fecha_nacimiento_empleado, fecha_ingreso_empleado, FK_depto_empleado, FK_id_nomina_empleado, FK_id_plantel_empleado) VALUES ('NEREBR', 'Nerea', 'Balaguer', 'Ripoll', 'NereaBR@howarts.com', 'a1b2c3d4', '1982-10-02', '2019-06-11', 204, 61, 501);

-- Table: jefes
DROP TABLE IF EXISTS jefes;
CREATE TABLE jefes (id_jefe INT PRIMARY KEY UNIQUE NOT NULL, nombre_jefe VARCHAR (0, 35) NOT NULL, apellido_pa_jefe VARCHAR (0, 20), apellido_ma_jefe VARCHAR (0, 20), correo_jefe STRING UNIQUE NOT NULL, Contrasena STRING NOT NULL, fecha_nacimiento DATE, fecha_ingreso DATE NOT NULL, FK_id_plantel INT REFERENCES plantel (id_plantel) NOT NULL, FK_depto_jefe INT REFERENCES departamentos (id_depto) NOT NULL, FK_id_nomina_jefe STRING REFERENCES nomina (id_nomina) UNIQUE NOT NULL);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('VIALGR', 'Vicente Alejandro', 'Gonz�lez', 'Rueda', 'alex1123.nel@gmail.com', 'adeuRVAGR.M', '2001-02-26', '2020-03-03', 501, 204, 1);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('TERECS', 'Teresita', 'Cerd�', 'Sainz', 'teresitaCS@howarts.com', 'a1b2c3d4', '1991-08-25', '2021-03-03', 501, 201, 2);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('ANDRSS', 'Andres', 'Salamanca', 'Sol', 'AndresSS@howarts.com', 'a1b2c3d4', '1980-11-03', '2021-01-08', 501, 202, 5);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('GRACZA', 'Gracia', 'Zurita', 'Armengol', 'GraciaZA@howarts.com', 'a1b2c3d4', '1995-10-14', '2015-02-18', 501, 203, 6);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('DELFAA', 'Delfina', 'Almeida', 'Azorin', 'DelgfinaAA@gmail.com', 'a1b2c3d4', '1991-08-15', '2015-10-08', 501, 205, 14);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('RAMOGC', 'Ramona', 'Gonz�lez', 'Carrasco', 'RamonaGC@howarts.com', 'a1b2c3d4', '1987-06-14', '2020-07-28', 502, 208, 25);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('ELIGHD', 'Eligio', 'Hernandez', 'de Cadenas', 'EligioHD@howarts.com', 'a1b2c3d4', '1985-06-28', '2020-04-19', 502, 207, 24);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('RUFIBB', 'Rufina Amanda', 'Bar�', 'Bravo', 'RufinaBB@howarts.com', 'a1b2c3d4', '1983-04-28', '2016-01-29', 502, 206, 23);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('RAFABC', 'Rafael', 'Batlle', 'Carreras', 'RafaelBC@howarts.com', 'a1b2c3d4', '1997-12-04', '2018-12-31', 502, 205, 22);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('GONZMT', 'Gonzalo', 'Morillo', 'Torres', 'GonzaloMT@howarts.com', 'a1b2c3d4', '1995-01-26', '2016-07-29', 502, 204, 21);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('ALEJGD', 'Alejandra', 'Garcia', 'de Ayll�n', 'AlejandraGD@howarts.com', 'a1b2c3d4', '1999-09-21', '2015-10-26', 502, 203, 20);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('CARICE', 'Carina Carmela', 'Cabrera', 'Enr�quez', 'CarinaCCE@howarts.com', 'a1b2c3d4', '1985-10-30', '2021-03-05', 502, 202, 19);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('DONADS', 'Donato', 'Di�guez', 'Sarabia', 'DonatoDS@howarts.com', 'a1b2c3d4', '1998-05-25', '2016-08-15', 502, 201, 18);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('ELIASC', 'El�as', 'Sanchez', 'Catal�n', 'EliasSC@howarts.com', 'a1b2c3d4', '1996-04-09', '2020-05-18', 501, 208, 17);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('JOSERS', 'Jose Miguel', 'Rosales', 'Sacrist�n', 'JoseMRS@howarts.com', 'a1b2c3d4', '1999-06-25', '2020-02-05', 501, 207, 16);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('ESTRHL', 'Estrella', 'Herranz', 'Lopez', 'EstrellaHL@howarts.com', 'a1b2c3d4', '1991-02-17', '2019-12-17', 501, 206, 15);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('HUGOBA', 'Hugo', 'Benet', 'Ariza', 'HugoBA@howarts.com', 'a1b2c3d4', '1985-01-01', '2015-09-28', 503, 201, 44);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('AUROSB', 'Aurora', 'Salda�a', 'Baeza', 'AuroraSB@howarts.com', 'a1b2c3d4', '1984-06-07', '2021-04-28', 503, 206, 43);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('MANUPC', 'Manu', 'Peinado', 'Carretero', 'ManuPC@howarts.com', 'a1b2c3d4', '1983-12-08', '2015-09-30', 503, 202, 42);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('GABRLT', 'Gabriela', 'Llabr�s', 'Tejedor', 'GabrielaLT@howarts.com', 'a1b2c3d4', '1992-07-21', '2018-12-06', 503, 204, 41);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('HERMOA', 'Herminia', 'Ortu�o', 'Angulo', 'HerminiaOA@howarts.com', 'a1b2c3d4', '1993-09-07', '2017-09-21', 503, 207, 40);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('TRINCA', 'Trinidad', 'Caro', 'Arellano', 'TrinidadCA@howarts.com', 'a1b2c3d4', '1981-02-25', '2019-06-18', 503, 203, 39);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('EPIFCJ', 'Epifanio', 'Cid', 'Jim�nez', 'EpifanioCJ@howarts.com', 'a1b2c3d4', '1982-06-26', '2019-02-15', 503, 208, 38);
INSERT INTO jefes (id_jefe, nombre_jefe, apellido_pa_jefe, apellido_ma_jefe, correo_jefe, Contrasena, fecha_nacimiento, fecha_ingreso, FK_id_plantel, FK_depto_jefe, FK_id_nomina_jefe) VALUES ('BRUNQB', 'Brunilda', 'Quintana', 'Baquero', 'BrunildaQB@howarts.com', 'a1b2c3d4', '1996-12-05', '2016-12-31', 503, 205, 37);

-- Table: nomina
DROP TABLE IF EXISTS nomina;
CREATE TABLE nomina (id_nomina STRING PRIMARY KEY UNIQUE NOT NULL, num_nomina INT UNIQUE NOT NULL);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (1, 546521);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (2, 789845);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (3, 789846);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (4, 749652);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (5, 469832);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (6, 213065);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (7, 901546);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (8, 605013);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (9, 597815);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (10, 301578);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (11, 113564);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (12, 121212);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (13, 131313);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (14, 149875);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (15, 215151);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (16, 254961);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (17, 506048);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (18, 354982);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (19, 362510);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (20, 518760);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (21, 263159);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (22, 223522);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (23, 315264);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (24, 948152);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (25, 309780);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (26, 789154);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (27, 568941);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (28, 289696);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (29, 292929);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (30, 356978);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (31, 316597);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (32, 948673);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (33, 306197);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (34, 645891);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (35, 651460);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (36, 497816);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (37, 879642);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (38, 489612);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (39, 319487);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (40, 134679);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (41, 794613);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (42, 163497);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (43, 197346);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (44, 283917);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (45, 938271);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (46, 555555);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (47, 679428);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (48, 674485);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (49, 505050);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (50, 278541);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (51, 649785);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (52, 496587);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (53, 487953);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (54, 319647);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (55, 585254);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (56, 595751);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (57, 535659);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (58, 181916);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (59, 272624);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (60, 164287);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (61, 234578);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (62, 851467);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (63, 135494);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (64, 163749);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (65, 251849);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (66, 436871);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (67, 167491);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (68, 254163);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (69, 187349);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (70, 487591);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (71, 315963);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (72, 187898);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (73, 123252);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (74, 454985);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (75, 762649);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (76, 183468);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (77, 923158);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (78, 267496);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (79, 346854);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (80, 174691);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (81, 999999);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (82, 222222);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (83, 324962);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (84, 946298);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (85, 842157);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (86, 134682);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (87, 524681);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (88, 487593);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (89, 214536);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (90, 518972);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (91, 712933);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (92, 586545);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (93, 428674);
INSERT INTO nomina (id_nomina, num_nomina) VALUES (94, 789259);

-- Table: permisos
DROP TABLE IF EXISTS permisos;
CREATE TABLE permisos (id_permiso INT PRIMARY KEY UNIQUE NOT NULL, tipo_permiso VARCHAR (0, 15) NOT NULL, proceso_permiso VARCHAR (0, 15) NOT NULL, motivo_permiso VARCHAR (0, 150), fecha_ini_permiso DATETIME NOT NULL, fecha_fin_permiso DATETIME, FK_id_empleado INT REFERENCES empleados (id_empleado), FK_id_jefes INT REFERENCES jefes (id_jefe));

-- Table: plantel
DROP TABLE IF EXISTS plantel;
CREATE TABLE plantel (id_plantel INT PRIMARY KEY UNIQUE NOT NULL, clave_plantel STRING UNIQUE, nombre_plantel VARCHAR (0, 50) NOT NULL);
INSERT INTO plantel (id_plantel, clave_plantel, nombre_plantel) VALUES (501, '501PNY', 'Plantel Nueva York');
INSERT INTO plantel (id_plantel, clave_plantel, nombre_plantel) VALUES (502, '502PLA', 'Planel Los Angeles');
INSERT INTO plantel (id_plantel, clave_plantel, nombre_plantel) VALUES (503, '503PMG', 'Plantel Texas');

-- Table: recuperacion
DROP TABLE IF EXISTS recuperacion;
CREATE TABLE recuperacion (id_recuperacion INT PRIMARY KEY UNIQUE NOT NULL, numero_ramdon_recuperacion INT UNIQUE NOT NULL, FK_id_empleado_recuperacion INT REFERENCES empleados (id_empleado), FK_id_jefe_recuperacion INT REFERENCES jefes (id_jefe));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
